# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "820ca3a4b5d54402edb1864d6f1f7b03"
name = "Any Kind of Filter Builder v2"
application_url = "https://any-kind-of-filter-builder-v2-production.up.railway.app"
embedded = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = ["https://any-kind-of-filter-builder-v2-production.up.railway.app/auth/callback"]

[app_proxy]
url = "https://any-kind-of-filter-builder-v2-production.up.railway.app"
subpath = "akf"
prefix = "apps"